#!/bin/sh

image_name=`uci get forcedata.@forcedata[0].image 2>/dev/null`

if [ "$image_name" == "jjm2473/forcedata-rtk:latest" ]; then
    uci -q batch <<-EOF >/dev/null
        set forcedata.@forcedata[0].image="default"
        commit forcedata
EOF
fi
exit 0
